apiVersion: learningcenter.tanzu.vmware.com/v1beta1
kind: Workshop
metadata:
  name: lab-carvel
spec:
  title: Carvel Lab
  description: Carvel Tools Workshop
  vendor: jeffgbutler
  difficulty: intermediate
  duration: 45m
  authors:
  - Jeff Butler
  url: https://github.com/jeffgbutler/lab-carvel
  content:
    files: github.com/jeffgbutler/lab-carvel?ref=main
  session:
    namespaces:
      budget: small
    applications:
      files:
        directory: exercises
        enabled: true
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
      editor:
        enabled: true
