#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Pod
metadata:
  name: kuard
  namespace: #@ data.values.namespace
  labels:
    name: kuard
spec:
  containers:
  - name: kuard
    image: gcr.io/kuar-demo/kuard-amd64:blue
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
